.gitignore, runner/dl_checkpoints.sh
This pull request ensures that the user's authentication token from 'huggingface-cli' is utilized for downloading models when the `HF_TOKEN` environment variable is unset.
Not a necessity just something I use on my own machine.
=> fix: hugging-cli token retrieval issue

runner/app/routes/image_to_video.py
This pull request improves the error handling for the width and height parameters in the image-to-video pipeline. It ensures that a
detailed JSON error response is returned when the width and/or height parameters are not divisible by 8, as required by the
[StableVideoDiffusion](https://github.com/livepeer/ai-worker/blob/907b8c203efa475c41f4c8325f20812da9b92d34/runner/app/routes/image_to_video.py#L55) pipeline. This enhancement aids in better debugging and user experience.
=> fix(image-to-video): enhance error handling for width/height parameters

runner/README.md
This pull request rectifies an error in the pipeline run commands documentation. Previously, the instructions incorrectly suggested naming the Docker container as 'runner'. This has now been corrected.
=> docs: correct pipeline run command instructions

runner/.devcontainer/devcontainer.json
This pull request ensures the model's folder is correctly mounted into the dev container. By default, the local container is mounted under the `/workspace` path when using a dev container. Because of this, the fp16 variant is not used, which causes the memory on smaller cards to be insufficient.
=> chore: fix devcontainer GPU memory bug

runner/.devcontainer/devcontainer.json
This pull request adds [Black Formatter](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) vscode extension to the Dev Container.
=> chore(devContainer): add black format extension to config

runner/app/pipelines/image_to_image.py, runner/modal_app.py
This pull request adds the [SDXL-Lightning](https://huggingface.co/ByteDance/SDXL-Lightning/blob/main/sdxl_lightning_samples.jpg) model to the image-to-image pipelines.
Fixes LIV-97
=> feat(runner): add support for SDXL-Lightning in image-to-image pipelines

runner/dev/Dockerfile.debug, runner/dev/README.md, runner/dev/patches/debug.patch
This pull request enhances the developer documentation with steps for debugging the AI runner container, including setup for DevContainer and attaching to running containers.
=> chore(runner): add debugging instructions for AI runner container 

runner/dl_checkpoints.sh
This pull request enhances the user experience when executing the 'dl_checkpoints.sh' script by providing more informative and timely feedback. It includes checks for 'huggingface-cli' installation and user login status, and provides clear instructions if these prerequisites are not met.
=> feat(runner): enhance user feedback in 'dl_checkpoints.sh' script

runner/dl_checkpoints.sh
This pull request introduces the `--alpha` command-line option to the `dl_checkpoints.sh` script. This allows AI subnet alpha participants to download only the models supported by Livepeer.inc's Gateway node during the alpha phase.
=> feat(dl_checkpoints): add --alpha option to checkpoint download script

runner/.devcontainer/devcontainer.json
This pull request adds an optional container mount for developers to uncomment when their models are located in the `.lpData` directory, as recommended in go-livepeer/ai-video.
=> chore(devcontainer.json): add optional mount for models

runner/Dockerfile, runner/app/cfg/uvicorn_logging_config.json
This pull request adds a uvicorn configuration file and uses this file during uvicorn startup to add timestamps to the uvicorn logs. The configuration is equal to the default configuration stored in `uvicorn.config.LOGGING_CONFIG` but with a timestamp prepended.
=> chore: add timestamp to uvicorn logs

runner/app/pipelines/image_to_image.py, runner/app/pipelines/image_to_video.py, runner/app/pipelines/text_to_image.py
This commit ensures that the model is pre-traced when [SFAST](https://github.com/chengzeyi/stable-fast) is enabled for the ImageToVideo pipeline. Without this pre-tracing the first request will be slower than a non SFAST call.
=> perf: pre-warm ImageToVideo SFAST pipeline

.flake8, runner/.flake8
This pull request ensures that the IDE does not throw flake8 errors due to incompatibilities between flake8 and black.
=> refactor: fix flake8 errors

runner/gen_openapi.py, runner/openapi.yaml
This pull request gives developers the ability to also export YAML based OpenAPI specs. These can be useful when wanting to create automatic API documentation using documentation software like https://mintlify.com/.
=> feat(runner): add ability to export YAML OpenAPI specs

worker/container.go, worker/docker.go, worker/worker.go
This pull request fixes a timeout bug that was introduced in #61 that caused external container loading to timeout before communication was established.
=> fix(worker): fixed external container timout bug

runner/dl_checkpoints.sh
This is not an issue, just good linting - https://www.shellcheck.net/wiki/SC2086
=> Double quote variables to prevent globbing

.gitignore, README.md, cmd/examples/image-to-image/main.go, cmd/examples/image-to-video/main.go, cmd/examples/text-to-image/main.go, dev/README.md, runner/.devcontainer/devcontainer.json, runner/README.md, runner/dev/README.md
This pull request improves both the documentation and developer documentation making it easier for developers to work with the AI worker and runner.
=> docs: improve general and development documentatation

worker/b64.go
This change adds support for uploading jpg, jpeg and gif file formats to the image-to-image workflow.
```
curl -X POST 0.0.0.0:8937/image-to-image -F image=@/home/elitedev/dog.jpeg -F prompt="a dog" -F model_id="ByteDance/SDXL-Lightning"
{"images":[{"seed":568555010,"url":"/stream/9aea34c2/6a3332f2.png"}]}
```
```
curl -X POST 0.0.0.0:8937/image-to-image -F image=@/home/elitedev/dog.jpg -F prompt="a dog" -F model_id="ByteDance/SDXL-Lightning"
{"images":[{"seed":3512476704,"url":"/stream/3b2f08fd/23daeba5.png"}]}
```
```
curl -X POST 0.0.0.0:8937/image-to-image -F image=@/home/elitedev/sample.gif -F prompt="a sky at the beach" -F model_id="ByteDance/SDXL-Lightning"
{"images":[{"seed":4239492,"url":"/stream/507072fa/34179043.png"}]}
```
=> feat(worker): add jpg, jpeg and .gif support in image-to-image pipeline (LIV-264)

runner/app/routes/image_to_image.py, runner/app/routes/image_to_video.py, runner/app/routes/text_to_image.py
This pull request ensure that all images are returned when a seed is set in the old code only the fist image of the badge was returned. Fixes LIV-309e.
=> fix(pipelines): fix image truncation bug when seed is set

runner/openapi.json
This pull request updates the OpenAPI server to the https://livepeer.cloud community gateway.
=> chore(runner): update OpenAPI spec server URI

runner/dl_checkpoints.sh
This pull request ensure that if the HF_TOKEN is not set the command can still execute if the user has logged in using the huggingface-cli.
=> fix: handle HF_TOKEN not set problem

runner/app/routes/image_to_video.py
This pull request ensures the response format of the I2V pipeline is correct, preventing a `nil` pointer runtime error on the Gateway side.
=> fix(I2V): Prevent `nil` pointer runtime error

worker/worker.go
This pull request ensures that an error is returned to the gateway when the runner container returns a successful but empty response.
=> fix(worker): throw error for empty container response

runner/app/routes/text_to_image.py
Updated the text-to-image to sequentially process images if more than 1 requested.
This provides more stable on GPU memory usage and I believe inference is relatively linear for text-to-image models.  If a user wants faster inference they can split the request to separate requests that would go to separate orchestrators.
This is a quick fix for issue [#49](https://github.com/livepeer/ai-worker/issues/49).
Some questions:
1) Should we set a sensible limit per request?  Timeout seems to be 30s so 15 sounds like a good limit that would allow most graphics cards to respond within the timeout.
2) Is there a check for if a set of images is requested but non-matching number of seeds is provided?  For example, batch of 10 requested but only 5 seeds provided.  I was not seeing where it would fill …
=> Process text-to-image requested image count sequentially

runner/dl_checkpoints.sh
This pull request ensures that a more descriptive error is thrown when the huggingface token is not set. Fixes https://linear.app/livepeer-ai-spe/issue/LIV-392/fix-huggingface-login-token-not-found-error.
=> fix: fix huggingface token not found error

runner/app/pipelines/image_to_video.py, runner/app/routes/image_to_video.py, runner/openapi.json, runner/openapi.yaml, runner/test.txt, worker/runner.gen.go
This PR integrates the [CompVis/stable-diffusion-safety-checker](https://huggingface.co/CompVis/stable-diffusion-safety-checker) into the `image-to-video` pipeline.  
The safety check is done on the input image of the request with the result carried through to the response. At this time, the
Similar to `the text-to-image` and `image-to-image` implementations the Orchestrator can opt to perform the safety check on the CPU using the `SAFETY_CHECKER_DEVICE` environment variable to conserve VRAM.  CPU processing will be slower than GPU but is up to the orchestrator to determine what is best to serve the request.
See [text-to-image](https://github.com/livepeer/ai-worker/pull/76) PR for performance results.
=> feat(image-to-video): integrate NSFW safety checker

runner/app/pipelines/image_to_image.py, runner/app/pipelines/text_to_image.py, runner/app/pipelines/util.py
This commit ensures that people can not use the [deepcache](https://github.com/horseee/DeepCache) optimization with lightning and turbo models. As explained in https://github.com/livepeer/ai-worker/issues/82#issuecomment-2141983903 this optimization does not offer any speedup for these models while it does reduce image quality.
=> feat(runner): disable DEEPCACHE for lightning/turbo models

runner/app/routes/image_to_image.py, runner/app/routes/text_to_image.py
This PR updates the image-to-image router in runner to process the batch requests sequentially.  Similar to text-to-image, this will stabilize GPU memory usage and allow for some GPUs to run multiple instances of lighter weight models.
=> fix(runner): update img2img to do sequential processing of batch request

runner/dl_checkpoints.sh
This pull request cleans up the download script to remove redundancy.
=> refactor(runner): remove redundancy in dl_script

worker/multipart.go
This pull request ensure that the multipart writers correctly forward the `safety_check` and `image_guidance_scale` parameters to the AI runner container.
=> fix(worker): ensure multipart writers correctly forward parameters

runner/app/main.py, runner/app/pipelines/upscale.py, runner/app/routes/upscale.py, runner/dl_checkpoints.sh, runner/gen_openapi.py, runner/openapi.json, runner/requirements.txt, runner/test.txt, worker/docker.go, worker/multipart.go, worker/runner.gen.go, worker/worker.go
add support to upscale images using _timbrooks/instruct-pix2pix_ model
=> add upscale image support to AI pipelines

runner/app/routes/image_to_video.py, runner/gen_openapi.py
This pull request ensures that the right format is set in the OpenAPI spec forwhen the I2I response is coming from the gateway. This is a little bit hacky since we don't yet generate the OpenAPI spec where it is implemented (i.e. in go-livepeer).
=> fix(api): fix incorrect I2I OpenAPI gateway spec

runner/requirements.txt
This pull request ensures that numpy<2.0.0 is used to prevent conflicts with Pytorch 2.1.1. We can upgrade these packages in the future (see https://github.com/pytorch/pytorch/issues/107302).
=> fix: pin numpy version to prevent conflits

runner/app/pipelines/text_to_image.py, runner/app/routes/text_to_image.py, runner/dl_checkpoints.sh, runner/requirements.txt
This pull request introduces support for the Stable Diffusion 3 Medium model from Hugging Face:
[https://huggingface.co/stabilityai/stable-diffusion-3-medium](https://huggingface.co/stabilityai/stable-diffusion-3-medium).
> [!WARNING]\
> If you put this model on your orchestrator please be aware that this model has restrictive licensing at the time of writing and is not yet advised for public use. Ensure you read and understand the [licensing terms](https://huggingface.co/stabilityai/stable-diffusion-3-medium/blob/main/LICENSE) before enabling this model on your orchestrator.
=> feat(runner): add support for SD3-medium model

runner/app/pipelines/text_to_image.py, runner/app/pipelines/utils/__init__.py, runner/app/pipelines/utils/utils.py
This PR enables requests to use multiple prompts supported by SDXL and SD3 with no API updates needed.  Diffusers uses the same prompt in all text_encoders if the prompts are not split.  Multiple prompts is supported by SDXL and SD3 models and can benefit from specializing the prompts to the different text_ecnoders if tuned properly.
The prompts are split by including a `|` at the point where want the prompts split.  
For SDXL see diffusers pipeline documentation here:https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl
Specifically the `prompt_2` input to the `__call__`: https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl#diffusers.StableDiffusionXLPipeline.__call__
For SD3 see diffusers pipeline …
=> enable multiple prompts for T2I

.github/workflows/validate-openapi-on-pr.yaml
This pull request adds a simple action that notifies developers when they forgot to update the OpenAPI spec or golang bindings.
=> ci: add PR OpenAPI/bindings check action

runner/app/pipelines/text_to_image.py, runner/dl_checkpoints.sh
This pull request ensures that the https://huggingface.co/SG161222/Realistic_Vision_V6.0_B1_noVAE model is supported in the T2I pipeline.
=> feat(model): add Realistic Vision model T2I support

.github/workflows/trigger-upstream-openapi-sync.yaml
This pull request adds an update trigger to the OpenAPI sync action that triggers an update of the JS/TS SDK.
=> ci: add JS/TS SDK update trigger

.github/workflows/trigger-upstream-openapi-sync.yaml
This action addes a trigger to update the OpenAPI spec in https://github.com/livepeer/ai-sdk-js. Furhter it improves the OpenAPI spec upstream sync action to forward more information.
=> ci: add TS/JS SDK OpenAPI spec update trigger

runner/app/pipelines/image_to_image.py, runner/app/pipelines/optim/sfast.py, runner/app/pipelines/text_to_image.py, runner/app/pipelines/upscale.py, runner/app/pipelines/utils/__init__.py, runner/app/routes/audio_to_text.py, runner/app/routes/image_to_image.py, runner/app/routes/image_to_video.py, runner/app/routes/upscale.py, runner/gen_openapi.py, runner/modal_app.py
This pull request sorts the python imports using the https://pypi.org/project/isort package.
=> refactor: sort imports using isort

.github/workflows/trigger-upstream-openapi-sync.yaml
This pull request ensures the right upstream repos are triggered in the trigger upstream OpenAPI sync action.
=> ci: update OpenAPI spec trigger repos

runner/app/pipelines/text_to_image.py, runner/requirements.txt, runner/test_prompts.py
This pull request adds support for the [Black Forrest Labs Flux 1 Schnell](https://huggingface.co/black-forest-labs/FLUX.1-schnell) model to the T2I pipeline. It is important to note that this model can only run on GPUs with more than 33 GB or VRAM.
=> feat(T2I): add Black Forrest Labs Flux 1 support

runner/gen_openapi.py
This pull request removes the health endpoint schema from the generated Gateway OpenAPI spec.
=> refactor: cleanup Gateway OpenAPI spec

runner/app/pipelines/image_to_image.py, runner/app/pipelines/text_to_image.py
Update text-to-image and image-to-image to 8 step unet for ByteDance/SDXL-Lightning model
=> Update ByteDance/SDXL-Lighting to default to 8step

runner/gateway.openapi.json, runner/gen_openapi.py, runner/openapi.json
This pull request ensures that the latest git release flag is applied to the OpenAPI spec.
=> feat: apply git release version to OpenAPI spec

.github/workflows/validate-openapi-on-pr.yaml
This pull request fixes the OpenAPI spec check action. This action can be used to ensure the OpenAPI spec and go bindings are up to date.
=> ci: fix OpenAPI spec check action

Makefile
This pull request ensures that the make file uses the right OpenAPI spec to generate the go bindings.
=> chore: update make go-bindings generation command

.github/workflows/ai-runner-docker.yaml
This pull request ensures that the main Docker container is also tagged as the base container so that it can be used as the base for the pipeline specific containers.
=> ci(docker): add ai-runner base Docker tag

.github/workflows/ai-runner-docker.yaml
This pull request ensures that the workflow dispatch triggers the docker job.
=> ci(docker): ensure docker ci dispatch works

.github/workflows/ai-runner-pipelines-docker.yaml
This pull request ensures that maintainers can manually run the pipeline docker ci.
=> ci(docker): enable pipeline docker workflow dispatch

runner/dl_checkpoints.sh
This change adds `facebook/sam2-hiera-large` to the beta models section of `dl_checkpoints.sh`
The [docs ](https://docs.livepeer.org/ai/orchestrators/models-download) instruct to use the `--beta` flag when running the bash script, which excludes this model. The change will improve orchestrator experience.
=> (chore) add sam2-hiera-large to beta models download

runner/Dockerfile
Dockerfile is missing `example_data` folder for bench.py to run. Built and tested the fix with `titannode/ai-runner:example-images`, works as expected.
=> Added example_data folder to Dockerfile

runner/app/routes/audio_to_text.py, runner/gateway.openapi.yaml, runner/openapi.yaml, worker/runner.gen.go
In the previous pull request, I adhered to the union type used by Whisper, but this caused issues in the multipart handling. To avoid complicating the MultiPartWriter, this commit converts the union type to a string. This change simplifies the multipart handling and user confusion.
=> fix: simplify A2T return_timestamps type

runner/app/pipelines/audio_to_text.py, runner/app/pipelines/image_to_image.py, runner/app/pipelines/image_to_video.py, runner/app/pipelines/text_to_image.py, runner/app/pipelines/upscale.py
[torch.device](https://pytorch.org/docs/stable/tensor_attributes.html#torch-device) is a class not a string, so directly compare them will also result in True
```
torch_device != "cpu" # this is always True, event when torch_device is torch.device('cpu')
```
=> fix torch device comparison

.github/workflows/ai-runner-pipelines-docker.yaml
This pull request prevents code duplication when more pipelines are added by using the GitHub action matrix syntax so that each pipeline is build based on its suffix.
=> ci: make pipeline docker ci more generic

runner/app/routes/text_to_image.py
This pull request adds a check to the T2I route to ensure the 'prompt' input value is non-empty. This is necessary because request body validation was disabled in go-livepeer due to issues with optional parameters not showing up correctly.
See [this go-livepeer commit](https://github.com/livepeer/go-livepeer/commit/3fcc300b42a0e758ebe63f2599a5556a5bd95390) for more details.
=> fix(runner): handle empty prompt in T2I input

runner/app/live/params_api/api.py, runner/app/live/streamer/streamer.py
There were some kwargs that were passed as args etc, made them consistent on all the stack.
=> runner/live: Fix params API params piping

runner/docker/Dockerfile.live-multimedia
Installing it takes a long time and it is no longer needed as far as I can tell.
This should reduce the image size significantly as well.
=> Remove gstreamer from live-multimedia Dockerfile

runner/app/cfg/uvicorn_logging_config.json, runner/app/pipelines/live_video_to_video.py
We need to read the stdout/stderr pipe from the subprocess (and if we don't it will eventually block)
Then change to uvicorn to log stderr instead of stdout, I have no idea what this actually does does but this is the only way to get `logger.info` to log in the subprocess - otherwise we only see lines from `logger.error`
(both are necessary)
=> Fix logging in live subprocess.

runner/app/live/infer.py, runner/app/live/streamer/jpeg.py, runner/app/live/streamer/process.py, runner/app/live/streamer/streamer.py, runner/app/live/streamer/trickle.py, runner/app/live/streamer/zeromq.py, runner/app/live/trickle/__init__.py, runner/app/live/trickle/jpeg_parser.py, runner/app/live/trickle/media.py, runner/app/live/trickle/segmenter.py, runner/app/live/trickle/trickle_publisher.py, runner/app/live/trickle/trickle_subscriber.py, runner/docker/Dockerfile.live-multimedia, runner/run-lv2v.sh
Logging is still rough as I'm ironing out issues around tear-down, but wanted to put this out
Should be testable with 
```
curl -vvv http://localhost:9000/live-video-to-video/ -H 'Content-Type: application/json' -d '{"subscribe_url":"http://trickle-server/input-stream","publish_url":"http://trickle-server/output-stream"}'
```
=> live/infer: Add trickle input and output

runner/.devcontainer/devcontainer.json, runner/Dockerfile, runner/docker/Dockerfile.segment_anything_2, runner/docker/Dockerfile.text_to_speech
This pull request ensures that the dev container can be successfully built when a pipeline Dockerfile is set. It also cleans up the COPY commands to use the WORKDIR instead of absolute paths for better readability and maintainability.
=> chore: fix dev container build

runner/app/pipelines/live_video_to_video.py
This change fixes an issue calling infer.py with unsupported parameters:
```
usage: infer.py [-h] [--http-port HTTP_PORT] [--pipeline PIPELINE]
[--initial-params INITIAL_PARAMS]
[--stream-protocol {trickle,zeromq}] --subscribe-url
SUBSCRIBE_URL --publish-url PUBLISH_URL [-v]
infer.py: error: unrecognized arguments: --input-address tcp://localhost:5555 --output-address tcp://localhost:5556
```
=> (lv2v) remove unsupported parameters

runner/app/live/trickle/jpeg_parser.py, runner/app/live/trickle/media.py, runner/app/live/trickle/segmenter.py, runner/app/live/trickle/trickle_publisher.py, runner/app/live/trickle/trickle_subscriber.py
Use `Lp-Trickle-Seq` as the header for sequence numbering
Better end-of-stream handling
Ignore SSL certificates since orchestrators generate them at runtime
Don't assume a fixed frame rate for output video; use what we have
Logging cleanup
=> live/trickle: Updates for go-livepeer

runner/app/live/streamer/streamer.py
On the LiveKit PoC we resized the images on the agent code, and were missing that part from this infer.py piece. This is probably one reason for the inference to be lower on the ai-worker as the resize still happened, but it happened on the same process as we run the model so it was competing for the same Python GIL (and resizing on CPU might be some relevant time).
=> runner/live: Make sure to resize images outside of infer process

runner/docker/Dockerfile.live-base-streamdiffusion
The diffusers and protobuf should come from the regular pypy repo, not the pytorch index.
=> runner/docker: Fix streamdiffusion deps installation

runner/app/live/streamer/streamer.py
The log afterwards was breaking
=> runner/live: Fix image resize logic to always set width,heiht

runner/app/live/streamer/process.py, runner/app/live/streamer/streamer.py, runner/app/pipelines/live_video_to_video.py, worker/docker.go
The shutdown logic needed some clean-up for the infer.py process, both internally and externally:
- internally, we needed to cleanup some multiprocessing resources so the main process is allowed to exit
- externally, we needed to use os._exit instead of sys.exit to exit the main app process
=> worker,runner: Fix lifecycle management of realtime containers

runner/app/live/streamer/streamer.py
It's not giving enough time for the pipeline to load and gets to an infinite loop.
=> live/runner: Increase liveportrait restart threshold

runner/app/live/infer.py
- It should not always start, only if control_url is sent
- It should get the PipelineStreamer, not the result of handler.wait()
=> api: Fix startup of control API

runner/app/live/infer.py
This change adds error handling to the `start_control_subscriber` task so that any invalid request or error in processing model parameter updates will not cause the control subscribe task to fail. 
Previously if an invalid request is sent, the control subscribe task will silently stop and will not process further requests.
=> Add error handling to control message handler task

worker/docker.go
@victorges @rickstaa Please review this PR to fix container return for managed containers inference.  
This was found from a report from an Orchestrator getting `insufficient capacity` error when using managed containers after the first request was completed.
I confirmed this was happening on my test machine and also confirmed it was happening on `ImageToImage` pipeline.
This fix delays the `return` in the `Borrow` function until after the `go m.watchContainer(rc, ctx)` is started.
=> fix: managed containers return after inference completed

runner/requirements-liveportrait.txt, runner/requirements.live-ai.txt
This change adds `nvidia-ml-py` to `requirements.live-ai.txt` and `requirements-liveportrait.txt` to resolve a missing import error in live pipelines.
The package was previously added to `requirements.txt`, however the live pipelines do not use this requirements file leading to a missing import error at runtime.
=> Add nvidia-ml-py to requirements

runner/app/live/infer.py
This change fixes an issue with the comfyui pipelines starting inference. It uses `asyncio.create_task(streamer.wait()))` instead of `streamer.wait()`.
Tested with managed/external containers and with both python 3.10/11
=> (chore) fix startup with asyncio.create_task

.github/workflows/ai-runner-live-pipelines-docker.yaml
docker builds are failing due to running out of space on the ubuntu24-04 runner, switching to oxford to un-break build for PR https://github.com/livepeer/ai-worker/pull/316
=> change github build action to run on oxford for live-pipeline builds

runner/app/live/infer.py
The control channel only sees sporadic messages, so the publisher will send down a keepalive periodically to prevent clients from timing out and to prevent the server from sweeping idle channels.
Needed for https://github.com/livepeer/go-livepeer/pull/3296 and https://github.com/livepeer/go-livepeer/pull/3299
=> runner/live: Ignore keepalive messages from control subscriber

.github/workflows/ai-runner-pipelines-docker.yaml, runner/app/pipelines/audio_to_text.py, runner/docker/Dockerfile.audio_to_text, worker/docker.go
This PR enables flash attention for `audio-to-text` pipeline. 
`runner/docker/Dockerfile.audio_to_text` can be used to build image for flash_attention_2 enabled A2T pipeline. `sdpa` attention implementation has been added in fallback condition for the GPUs that don't support flash attention. `sdpa` also improves the latency.
=> feat: add flash_attention_2 to audio_to_text pipeline's attn_implementation

.github/workflows/ai-worker-test.yaml
This pull request ensures that the worker tests use the same go version as defined in the go.mod file.
=> ci(worker): update go version

.github/workflows/ai-worker-test.yaml
This pull request makes use of the `go-version-file` option and caching behavoirs of the `actions/setup-go` action so that we don't have the CI throw a go version error.
=> ci(worker): fix worker test ci go version error

runner/requirements.live-ai.txt
We added to the main requirements file tho we don't use that from the live runner, 
so gotta add to the live-ai requirements too. We later need to figure this out so we 
don't need to duplicate deps.
=> runner/req: Add pynvml dependency

runner/app/live/infer.py
This change caused an issue with `update_params`. We have also switched to python 3.10 for the pipelines, so this should be reverted for now.
=> Revert "(chore) fix startup with asyncio.create_task"

runner/app/live/trickle/media.py, runner/app/live/trickle/trickle_subscriber.py
We weren't properly closing the sessions before so there was a warning from aiohttp
=> runner/live/trickle: Fix publisher/subscribe lifecycle

.github/workflows/ai-runner-live-pipelines-docker.yaml
This pull request temporarily disables the `cancel-in-progress` option due to issues in the `LivePortrait` runner, which prevent us from pushing new ComfyUI containers (see )
=> ci(runner): temporarily disable pipeline concurrency cancellation

.github/workflows/ai-runner-live-pipelines-docker.yaml
This pull request prevents the pipelin docker CI to run on the self-hosted mac machine since it causes docker hub authentication issues.
=> ci(runner): prevent pipeline docker CI from running on mac

.github/workflows/ai-runner-docker.yaml, .github/workflows/ai-runner-live-pipelines-docker.yaml, .github/workflows/ai-runner-pipelines-docker.yaml
This pull request ensure that if one container build fails the other containers still are build.
=> ci(runner): disable fail fast for batch docker ci

runner/docker/Dockerfile.live-base-streamdiffusion
Mainly to revert back to the main StreamDiffusion repo installation which uses `diffusers===0.24.0`
0.30.0 breaks it
Also removed other extraneous dependencies being installed in the dockerfile though.
=> runner/docker: Fix streamdiffusion base image

runner/dl_checkpoints.sh
I believe that `--interactive` and `--tty` (`-it`) was placed inside the non-interactive bash script by mistake.
It makes it problematic to run with ansible.
=> Fix dl_checkpoints.sh: don use `-it` flag when running docker containers

runner/dl_checkpoints.sh, runner/docker/Dockerfile.live-base-comfyui
Update streamdiffusion node to include improvements in :
https://github.com/pschroedl/ComfyUI-StreamDiffusion/pull/5
Updates DL_checkpoints to pull .safetensor checkpoint files as expected by new loading mechanism.
This should probably be fixed upstream in the node to use proper HF caching. Attempts were made to symlink the existing huggingface-cli downloaded models but that approach is not straightforward and this is a workaround that should be revisited.
=> bump commit hash for streamdiffusion node, update dl_checkpoints.sh

.github/workflows/ai-runner-docker.yaml, .github/workflows/ai-runner-live-pipelines-docker.yaml, .github/workflows/ai-runner-pipelines-docker.yaml
This pull request enables the `cancel-in-progress` setting for feature branches, while keeping it disabled on the main branch. This ensures that all Docker containers on the main branch are built without interruption. For feature branches, new commits will cancel any in-progress workflows, speeding up development times by allowing engineers to quickly push new changes.
=> ci(runner): enable docker build cancel-in-progress on feature branches

runner/app/live/pipelines/comfyui.py
This improves the ComfyUI params validation by:
- Creating a pydantic model to validate the provided input, similar to other pipelines
- Accepting the prompt as a string as well, which seems to be what the showcase app is sending for now. We make sure to parse it and send it as a JSON to comfystream, which is what they expect
=> runner/pipelines: Accept ComfyUI prompt as a string

runner/app/live/streamer/streamer.py
- change timestamps to int ms instead of float sec
- add a `timestamp` to every event as well (incl status, from the time we send)
=> streamer: Improve timestamp logic on status reporting

runner/app/live/streamer/streamer.py
We call the stop/restart function from coroutines that will be stopped as well by such functions. As such we should not await them otherwise there will be a recursive cancellation happening.
The right way is to create_task and let them execute in backgrund.
=> runner/streamer: Fix nested process restart

runner/app/live/streamer/process.py, runner/app/live/streamer/streamer.py
Refactor the pipeline status reporting to better match the spec from: 
https://www.notion.so/livepeer/Status-API-requirement-doc-WIP-6a35ccdf856343f8ad47b65a7a159403
=> runner/live: Improve pipeline status schema

runner/docker/Dockerfile.live-base-comfyui
Florence 2 comfyui node was optimized and provides better FPS with caption_to_phrase_grounding.
Have something else exploring and may have another bump later today so ok to hold off until later today.
Should we remove the commit ref for now? Or ok to bump it a few times here and there?
=> update: Florence 2 commit for optimizations

runner/dl_checkpoints.sh, runner/docker/Dockerfile.live-base-comfyui
Performance updates to ComfyUI_StableDiffusion from:
https://github.com/pschroedl/ComfyUI-StreamDiffusion/pull/6
Example Workflow Updates:
https://github.com/pschroedl/ComfyUI-StreamDiffusion/pull/7
Node now loads safetensor files ( full huggingface checkpoint loading is broken ), this PR adds checkpoints for:
sd_turbo.safetensors, kohaku_v2.1.safetensors and
https://huggingface.co/chenxxiao/3dCartoonVision_v10
and lora : ral-dissolve1.5
https://civitai.com/models/245889?modelVersionId=314246
=> update comfui_stablediffusion, add checkpoints and lora

runner/app/live/trickle/trickle_subscriber.py
Defaults to 5 retries with a 500ms sleep in between.
Exits on a 404 (trickle channel does not exist)
Also detects the case where the trickle channel exists but the segment in the sequence does not (via special status  code 470) and jumps to the leading edge.
See server implementation adding status code 470 support: https://github.com/livepeer/go-livepeer/pull/3327
=> trickle: Add reconnects in subscriber.

runner/app/live/infer.py, runner/app/live/streamer/process.py, runner/app/live/streamer/protocol/protocol.py, runner/app/live/streamer/protocol/trickle.py, runner/app/live/streamer/protocol/zeromq.py, runner/app/live/streamer/streamer.py
After working on #371 I realized how messy the lifecycle management of the streamer was.
This is to simplify and improve that a bunch.
Previously, we started a bunch of loose background tasks and had no central way of controlling them.
There were mainly 2 issues:
- Some of the tasks were started/restarted together with the inference process. This caused an additional complexity in the tasks themselves and in the task management logic.
- The stop() function was called from several different places, including from the tasks themselves that were being restarted. The restart function also killed some of the tasks that called it (cause they were recreated with the process).
So this improved this 2 issues in 2 steps:
- First made sure that all the asyncio tasks are started with the streamer …
=> live/streamer: Fix streamer shutdown logic

runner/app/pipelines/audio_to_text.py, runner/app/pipelines/utils/audio.py
PR improves file handling of `audio-to-text` pipeline by removing call to ffmpeg to process the audio and uses pyav to convert to raw audio.
Cloud SPE test file fails in my testing sometimes with current conversion implementation using "mp3" container and format. The processing error was coming from the internal conversion to raw audio in transformers (links below). Switching to processing the audio file using `pyav` allows the Cloud SPE file to process correctly.
Transformers calling ffmpeg binary from `preprocess` function.
https://github.com/huggingface/transformers/blob/47c29ccfaf56947d845971a439cbe75a764b63d7/src/transformers/pipelines/automatic_speech_recognition.py#L353
https://github.com/huggingface/transformers/blob/47c29ccfaf56947d845971a439cbe75a764b63d7/src/transformers/pipelin …
=> feat: update A2T audio conversion

runner/dl_checkpoints.sh
By default `docker run` runs as `root` and that mixes `/models/` dirs and files ownership
=> dl_checkpoints.sh - docker run as a user not the root

worker/docker.go, worker/docker_test.go, worker/worker.go
Towards closing ['livepeer/bounties/#69](https://github.com/livepeer/bounties/issues/69)
This PR adds support for processing JSON string in `defaultImage`and specifies pipeline-specific images as key-value pairs with their mappings being updated to override `containerImage`.
`go-livepeer` PR which it supports is [#3284](https://github.com/livepeer/go-livepeer/pull/3284)
cc @rickstaa
=> Support for JSON string in defaultImage field for overriding pipeline specific images in the mappings 

runner/dev/README.md
This pull request fixes a small developer documentation typo.
=> docs(runner): fix small dev documentation typo

docs/runner-docker.md, runner/app/live/infer.py, runner/app/live/pipelines/comfyui.py, runner/app/live/streamer/streamer.py, runner/app/live/trickle/media.py, runner/build.sh, runner/dl_checkpoints.sh, runner/docker/Dockerfile.audio_to_text, runner/docker/Dockerfile.live-app__PIPELINE__, runner/docker/Dockerfile.live-base-comfyui, runner/docker/Dockerfile.text_to_speech, runner/requirements.live-ai.txt
This implements the [task](https://www.notion.so/livepeer/Migrate-ai-runner-docker-to-comfystream-base-image-1890a348568780c1ae9ef2ee26fced82?pvs=4) for reusing `comfystream` base docker image
to avoid setting up a separate environment altogether for the `comfyui` ai-runner.
=> docker: Use comfystream base image as base for comfyui pipeline

runner/app/live/streamer/protocol/trickle.py
Temporary workaround to ensure that audio gets passed through instead of potentially dropped if the input queue is full.
=> Bypass input / output queues for audio.

.github/workflows/ai-runner-live-pipelines-docker.yaml
streamdiffusion dependencies with the new comfyui image needs to be resolved before these builds begin passing. The streamdiffusion pipeline is not required at launch so disabling it temporarily here.
=> workflows: disable streamdiffusion builds temporarily

.github/workflows/ai-runner-live-pipelines-docker.yaml, runner/app/main.py, runner/docker/Dockerfile.live-app__PIPELINE__, runner/requirements.live-ai.txt, runner/requirements.txt
Add a prometheus metric to record the version of the code running, so that we can track this in our dashboards.
=> Add a version metric

runner/app/live/api/api.py, runner/app/live/infer.py, runner/app/live/log.py, runner/app/live/streamer/__init__.py, runner/app/live/streamer/process.py, runner/app/live/streamer/process_guardian.py, runner/app/live/streamer/streamer.py, runner/app/pipelines/live_video_to_video.py
We want to improve cold start time for a stream so can't afford the isolation of
having one process per stream. Restructure infer.py so it is started with the
whole container and re-used across streams.
This was accomplished by removing the process-managemenet logic from the Streamer
and moving to an outer process guardian, then only create ephemeral streamers that use
the process guardian. 
The infer.py now exposes an API to be called to start the streamer as well which is
called from the runner API. The process is started immediately with the runner API
startup (from pipeline creation).
=> infer.py: Run a single pipeline process for all streams

runner/app/live/streamer/process.py, runner/app/live/streamer/process_guardian.py
It's difficult to trace why control api is failing in staging. Add a few logs to make it easier to debug.
=> streamer: add logging to debug control api failures

runner/app/live/log.py, runner/app/routes/live_video_to_video.py, runner/app/routes/utils.py, runner/gateway.openapi.yaml, runner/openapi.yaml
This is a dependency for https://github.com/livepeer/go-livepeer/pull/3408 We want explicit fields in the request and response bodies for requestIDs.
This change also means the runner accepts the IDs in the request body as well as headers, so we can switch the caller over to use the request body and then remove the headers.
=> Add request ID fields to request and response body schemas

runner/app/live/pipelines/comfyui.py, runner/docker/Dockerfile.live-base-comfyui
The changes in this base image tag are minimal, but are intended to address this error:
```
File "/workspace/miniconda3/envs/comfystream/lib/python3.11/site-packages/torch/_inductor/cudagraph_trees.py", line 336, in get_obj
assert torch._C._is_key_in_tls(attr_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
The tag `livepeer/comfyui-base:ai-runner-9166aa9` is cut from this branch 
https://github.com/yondonfu/comfystream/commits/ai-runner/
The warmup workflow in `runner/app/live/pipelines/comfyui.py` has been updated to :
https://github.com/yondonfu/comfystream/blob/beb6665f9e431fec72f0bbaccb1d628b47b14bdb/workflows/comfystream/sd15-tensorrt-api.json
The default workflow in supabase for staging should be updated when this is merged, and the `build_ai_models` github action should …
=> bump comfyui-base to latest-ai-runner-9166aa9

runner/app/live/streamer/streamer.py
Not sure why this works but it fixes the delay on tearing down a stream where we would have to wait for no inpu for 60 seconds.
=> Fix delayed teardowns

runner/app/routes/live_video_to_video.py
Previous attempt was causing the `multiple values` comfyui error, this is to fix that and add streamID back into the logs.
=> Fix setting streamID

runner/app/live/pipelines/comfyui.py, runner/app/live/streamer/process.py
Excessive 'INFO' logging may be slowing down pipelines.
This sets the log level to WARNING for the `comfy` package in the pipeline process and removes logs such as:
```
timestamp=2025-03-07 21:30:14 level=INFO location=model_management.py:629:_load_models_gpu gateway_request_id=8d6efc9d stream_id= message=Loaded <LoadedModel <ModelPatcher for BaseModel (model_dtype=torch.float16 device=cuda:0 size=7.8 KiB operations=disable_weight_init)>>
```
Attempts to use config arguments to ComfystreamClient did not produce the same results:
runner/app/live/pipelines/comfyui.py:270
```
self.client = ComfyStreamClient(cwd=comfy_ui_workspace, verbose='WARNING', logging_level='WARNING')
```
had no effect.
=> Set logging level for comfy package to WARN

runner/app/live/streamer/protocol/last_value_cache.py, runner/app/live/streamer/protocol/trickle.py, runner/app/live/trickle/encoder.py, runner/app/live/trickle/media.py
This requires adding a last value cache for the media metadata rather than pulling the metadata from a queue, because the queue may be empty when the encoder restarts.
We also need to explicitly close the write end of any pipes that may be dangling after the exception, since pyav will no longer be closing those.
=> trickle: Retry encoder if necessary

.github/workflows/ai-runner-docker.yaml, .github/workflows/ai-runner-live-pipelines-docker.yaml
we kept using the same build cache layer for go-livepeer and all ai-runner pipeline docker images (base/app/noop). this led to all docker builds being able to utilise 0% of cache as it kept getting overwritten.
=> workflows: Fix docker build cache being overwritten across repo

runner/app/pipelines/live_video_to_video.py
It has been misleading investigations to include the stack trace of the health check failure, since it looks like there is where the problem is on the code. Since the exceptions we get here are generally just problems with the healthcheck itself like the server being down or hanging, we better just log the error message.
=> lv2v: Omit misleading healthcheck stacktrace

runner/app/main.py
We were leaving the log_level to the default, which for some reason meant we were only logging ERROR level onwards (even tho python docs say it would log everything).
I didn't spend too much time understanding why that was the case, but configuring the logs like this fixes the issue and we get all INFO logs (or DEBUG if verbose is set). So we'll be in a better place to debug the infer.py crashes.
=> main: Configure logging level based on env

runner/app/live/streamer/process_guardian.py
Currently the runner will return IDLE on the healthcheck when a stream is starting and hasn't processed any input frames yet. Gotta give it some graceful startup time. This fixes it in a simple way by defaulting the `last_input_time` to the `start_time` of the stream (`start_time` is reset on `reset_stream`).
=> live/streamer: Avoid IDLE state in the beginning of stream

runner/app/pipelines/live_video_to_video.py, runner/requirements.txt
This is to add further monitoring to the infer.py process by periodically logging
information about the process collected from the OS. We also log such information
when we realize that the process exited or when the healthcheck failed with an
exception (not when it fails with a normal HTTP response, which means the process
is fine).
=> lv2v: Log process diagnostics periodically

runner/app/live/infer.py, runner/app/pipelines/live_video_to_video.py, runner/requirements.txt
This creates custom uncaught exception handlers for both asyncio and threading modules,
to make sure we crash the whole process when our code fails to handle an exception.
This is important to catch problems where we are forgetting to handle exceptions and part
of the runner stop working without notice. On the worst case when those exceptions are not
to be fatal, all we need to do is to add an try/except clause and log them. They should not be
uncaught. This is the default behavior in other envs like node and go and idk why python likes
to be the weird one.
=> lv2v/infer.py: Set uncaught exception handlers to terminate process

runner/app/live/streamer/process.py
When loading the process with default params we might end up with a `pipeline=None`
since the exception handler will only log the exception in case the initial params are already
empty (which means default).
This fixes by just re-raising the exception and crashing the process when the default params
fail to load.
=> live/process: Fail fast when pipeline can't be loaded

runner/app/live/streamer/process.py, runner/app/live/streamer/protocol/trickle.py
Clear queues each time there is a new stream.
I _believe_ this PR will fix https://linear.app/livepeer/issue/ENG-2582/runner-encoder-av-crash (Runner Encoder AV Crash). This is what happens:
1. Sometimes the queues are not cleared
2. Then, during the next stream the first read frame is from the previous stream
3. Then, encoder crashes, because the timestamps do not match
=> Reinitialize loops for each stream (fix AV Encoder Crash)

runner/app/live/streamer/process.py, runner/app/live/streamer/streamer.py, runner/app/live/trickle/frame.py
We recently started noticing issues where frames from the previous streams were delivered to the new
streams. It seems like the fix [didn't really work](https://eu-metrics-monitoring.livepeer.monster/grafana/explore?schemaVersion=1&panes=%7B%22che%22:%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22live-video-to-video_comfyui_8900%5C%22%7D%20%7C%3D%20%5C%22Invalid%20argument:%20%27%25d.ts%27%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22code%22,%22direction%22:%22forward%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1). Let's add it on debug logs so we can debug.
=> streamer: Debug log for each frame streamId

runner/app/live/streamer/process.py, runner/app/live/streamer/streamer.py, runner/app/live/trickle/frame.py
- Change the DEBUG log from `stream_id` to `request_id` (I think it's the `request_id` that represents the single streaming session in our system)
- Add frame dropping in case the frame request ID does not match the request ID currently being processed by the Runner
=> Encoder error workaround

.github/workflows/ai-runner-models.yaml
`dl_checkpoints.sh --tensorrt` runs directly on the single rtx-4090 server so make sure they won't interfere with other simultaneous builds as they don't run inside docker
=> make sure we run only one dl_checkpoints.sh at a time

runner/dl_checkpoints.sh
Adds a new depth anything engine compilation to `dl_checkpoints.sh` for `depth_anything_v2_vitl-fp16.engine`
This change is for https://github.com/livepeer/comfystream/pull/79 and requires the additional `depth_anything_v2_vitl.onnx` model from here https://github.com/livepeer/comfystream/pull/79/files#diff-2ecea05f303168744235a97f61ba4f203f75083eabd103e0ed223866bdd2b296R26
=> add depth-anything-large engine to dl_checkpoints.sh

runner/dl_checkpoints.sh
Reverting since this cannot be merged until after live-base-comfyui is updated with https://hub.docker.com/layers/livepeer/comfyui-base/latest/images/sha256-df93313a4a01c4b5197fcdd5e75c1c4eb85e4cfcc9ce8e1066926beaeb69db44 (the new model is not in models.yaml until this version)
Will reopen with this change after we're ready to ship new comfyui-base image
=> Revert "add depth-anything-large engine to dl_checkpoints.sh"

runner/app/live/pipelines/comfyui.py, runner/app/live/pipelines/noop.py
This seems to have broken in https://github.com/livepeer/ai-runner/pull/479
Even with this PR, it still doesn't run due to this line expecting a hard-coded path to python that doesn't exist:
https://github.com/livepeer/ai-runner/blob/9e21e45480bf3112388f5b4b6bfb11df3ea51522/runner/app/pipelines/live_video_to_video.py#L110
When I change the executable back to `python` for local testing then it works fine, but presumably it was changed for a reason so I am not sure the best way to sort that out, maybe by updating the PATH env var in the container instead of hard-coding it here.
=> Fix noop pipeline

runner/app/pipelines/live_video_to_video.py, runner/dl_checkpoints.sh
This change runs the noop pipeline normally and ensures the comfyui pipeline is started in the comfystream environment
=> fix: use conda env only when pipeline is comfyui

runner/app/live/api/api.py, runner/app/pipelines/live_video_to_video.py
This makes sure our recovery from process crashes is faster. Instead of relying on
gateway timeouts to detect the runner went away, and on worker timeouts to realize
the process crashed:
- Restart the `infer.py` process directly from the API process
- Upon startup, make sure we cleanup the previous stream trickle channels to notify gateway immediately
On the second item, cleaning up the previous stream, I had thought of a different
implementation where the runner API kept the "previous params" state instead. This would
be less future-proof tho, since we'd lose this integration point once we remove the infer.py
as a separate process. The current implementation is also more resilient against docker container
crashes, we'd just need to write the last params file on a mounted volume (left …
=> lv2v: Restart infer.py process and cleanup previous stream quickly

runner/dl_checkpoints.sh
[The script that gets downloaded](https://raw.githubusercontent.com/yondonfu/comfystream/535c71a6f665bc1169d07cddd4e2b3cf4edd5a82/src/comfystream/scripts/build_trt.py) does not expose the new parameters.
However, the PR that puts the correct script in the image [has been merged](https://github.com/livepeer/comfystream/blob/22c60af78715badc5db1447e3b0ccf9f43446d31/src/comfystream/scripts/build_trt.py#L86-L90). After pulling the latest version, I was able to run the script with the min/max width/height parameters.
=> Fix `dl_checkpoints.sh`

runner/app/live/trickle/media.py
We still get encode_av errors sometimes so let's see if retrying helps this time, instead of shutting down the stream.
=> Re-enable encoder retries.

runner/app/live/streamer/protocol/last_value_cache.py
Fixes an exception ... don't think this has happened in prod but I managed to trigger it somehow in dev.
=> Add missing logging import to last-value-cache

runner/app/pipelines/llm.py, runner/app/routes/utils.py, runner/requirements.llm.in
Updates llm docker image and pipeline to use vllm 0.8.4. 
This fixes security bug in 0.6.5 that llm pipeline currently uses.
Additional updates:
- cleanup commented out code
- add hardware info reporting requirements.
=> update to vllm 0.8.4

runner/app/live/trickle/decoder.py, runner/app/live/trickle/media.py
This isn't the most elegant approach since there may still be junk left over in the pipe but the ffmpeg mpegts demuxer will sync up correctly both to a start marker and an IDR, provided that the keyframe interval isn't too long.
=> Retry decoder if it throws an exception.

runner/app/live/pipelines/comfyui.py, runner/app/live/streamer/process.py
We've been having a couple issues in prod that I believe are related to a broken cleanup logic
for the `comfyui` (comfystream) pipeline. My theory for what happens is:
- `process_guardian` tries to kill the process for some reason (e.g. inference hanged)
- calls `pipeline.stop()`, but t he implementation on comfyui calls a `cleint.stop()` which doesn't exist
[`Error stopping pipeline: 'ComfyStreamClient' object has no attribute 'stop'`](https://eu-metrics-monitoring.livepeer.live/grafana/goto/ZgaViZxHR?orgId=1)
- comfystream never shuts down, its tasks stay running
- Joining the process fails because asyncio loop never ends
- [Kill leaves the process zombie and sometimes consuming a whole core](https://discord.com/channels/423160867534929930/1366364524944425020/1366364882454446100)
- New …
=> live/process: Fix ComfyUI pipeline cleanup

runner/app/live/streamer/process.py, runner/app/live/streamer/process_guardian.py, runner/app/live/streamer/status.py, runner/app/pipelines/live_video_to_video.py
We've been getting production issues where we can't restart the inference process anymore
as it hangs to the GPU and doesn't let new processes start up. We are fixing that problem, but
while we figure it out this is to avoid having zombie runners sticking around indefinitely.
2 extra changes:
- added a quick fix to also restart inference process immediately in case it exits (together with the temp fix, it means immediately shutting down the runner)
- actually built a new state to the pipeline runner which is propagated to the worker. the idea is that we can return this `ERROR` state with some other logic as well (e.g. we're restarting process a couple times and it doesn't work). 
- Right now the worker will still wait for 2 consecutive `ERROR`s before restarting the container, 
but in the …
=> live/streamer: Shut down runner on inference process restart

runner/app/live/trickle/trickle_publisher.py, runner/app/live/trickle/trickle_subscriber.py
This helps mitigate a bit of delay if the runner starts subscribing to a channel after the first segment has already started writing. This would have made the runner start waiting for the *next* segment (1s on average, up to 2s), which seems to happen roughly 2/3s of the time by eyeballing this histogram. Requires https://github.com/livepeer/go-livepeer/pull/3552
=> trickle: Start subscribing at the current seq, rather than the next

runner/app/live/streamer/process.py, runner/app/live/streamer/process_guardian.py, runner/app/live/streamer/streamer.py
This is to make sure we (the gateway/app) quickly failover to a different runner when the inference
process crashes. Otherwise they would have to wait for at least 30s until it comes back.
The risk of this change is in case someone finds out a prompt that always crashes the process. This 
would make it a kryptonite that could take our whole infra if the gateway/app retries indefinitely 💥 
We haven't seen any of that until now + if we have a reasonable number of app/gateway retries this
could be somewhat safe to merge anyway. 
This is built on top of #549 but is unrelated. Only implemented together but decided to put out for review separately.
=> live/streamer: Quick stream failover on process restart

runner/app/live/trickle/trickle_subscriber.py
Sometimes we get Timeouts (default ~5 minutes) if for some reason the orchestrator does not close the trickle channel.
This would be an uncaught exception that crashes the process so just catch everything here to avoid any crashes.
=> Catch all exceptions from trickle subscribe preconnects.

runner/app/live/trickle/media.py
Previously stopping the decoder would not stop any other processing except for blocking trickle subscriptions (due to the pipe being full) and the runner would be waiting until inference times out after 60 seconds of no input.
Here we fix this by signaling two things:
* Shut down the trickle subscriber by closing the end of the file descriptor that it writes into. This in turn ends the run_subscribe function.
* Send an empty input frame to inference to force the rest of the process to shut down, because run_subscribe stopping on its own apparently does not trigger any other teardown.
=> Shut down job if decoder stops.

runner/app/live/streamer/streamer.py, runner/app/live/trickle/decoder.py
We are currently resizing the input frames to 512 pixels, but we set the _lowest_ dimension
to 512. This means that we will downscale further than necessary, then crop and _upscale_
back the image on [the `streamer` side.](https://github.com/livepeer/ai-worker/blob/d06894afd00ef16eb3a09b296d56866d146f3c9d/runner/app/live/streamer/streamer.py#L196)
I tried looking around for a while to see if there was a way to crop the `VideoFrame` from within
pyav, but apparently there is not. The solution would be converting the frame to a numpy array
and cropping it there, which is exactly what we are doing on the streamer side anyway. To avoid 
duplication, I kept only the resize on the pyav decode logic, and only made sure we  don't call a
noop cv2 resize on the streamer side in case it was already …
=> live/trickle: Avoid downscaling input frames more than necessary

runner/app/live/api/api.py, runner/app/live/infer.py, runner/app/live/streamer/process.py, runner/app/live/streamer/process_guardian.py, runner/app/live/streamer/status.py, runner/app/live/streamer/streamer.py, runner/app/pipelines/base.py, runner/app/pipelines/live_video_to_video.py
This is to rewrite the monitor logic in the process guardian/streamer both to simplify it 
as well as make it more reliable.
This implements INF-119
- Independent logic on process guardian to restart process and streamer to declare state
- Passive, state was only computed/updated when requested on healthcheck
- All the other problems described in the issue
- Centralized state tracking on a single place: process guardian monitor loop
- It runs every 1s and computes the current state
- When the state is ERROR, it tries restarting the process up to 3 times
- ERROR state is sticky, until process gets restarted or container is killed
- State is updated on the status accordingly
- Shorter timeouts for errors:
- 5s not producing output frames (after being active)
- 30s not loading the pipeline …
=> live/streamer: Improve monitor loop reliability

runner/app/live/pipelines/comfyui.py
PR fixes the update_params fail params state mismatch. 
if the update fails in ai-runner it automatically assumes previous params but in comfystream it needs to be updated first and then its run so there is a mismatch
comfystream fix: https://github.com/livepeer/comfystream/pull/241
=> fix: params revert fallback

.devcontainer/devcontainer.json, docs/runner-docker.md, runner/Dockerfile, runner/dev/Dockerfile.debug, runner/dev/README.md, runner/docker/Dockerfile.llm
@leszko here is PR to add the VERSION tag to batch pipelines docker image and updates docs to add `--build-arg VERSION=$(./print_version.sh)` to the docker build commands
Fixes https://github.com/livepeer/ai-runner/issues/594
=> add VERSION to other docker image builds and update docs

.github/workflows/streamdiffusion-docker.yaml, runner/app/live/StreamDiffusionWrapper/__init__.py, runner/app/live/StreamDiffusionWrapper/build_tensorrt.py, runner/app/live/StreamDiffusionWrapper/wrapper.py, runner/app/live/pipelines/interface.py, runner/app/live/pipelines/loader.py, runner/app/live/pipelines/streamdiffusion.py, runner/app/live/streamer/process.py, runner/dl_checkpoints.sh, runner/docker/Dockerfile.live-app__PIPELINE__, runner/docker/Dockerfile.live-base-streamdiffusion, runner/requirements.live-ai.txt
This is to bring back the `streamdiffusion` pipeline that had been removed on #461.
The process was mainly to revert the relevant changes and then adjust any interface that changed
so it works on the new world. We have actually made several improvements to the pipeline since then
and this works much more performant than before.
**On my dev server, the comfystream pipeline performs 21 FPS while this works at 40 FPS.**
Use the box to test this: https://github.com/livepeer/go-livepeer/pull/3602
=> pipelines: Bring back the native streamdiffusion pipeline

runner/app/live/pipelines/streamdiffusion.py, runner/app/tools/streamdiffusion/build_tensorrt.py, runner/app/tools/streamdiffusion/build_tensorrt_internal.sh, runner/dl_checkpoints.sh, runner/docker/Dockerfile.live-base-streamdiffusion
This is to implement support for the controlnet pipeline described by the config yaml in the end
of this description.
Converted the format to the JSON params already received by the pipeline and added dependencies
for executing the provided controlnets. The default params were made to match that config yaml, but
it could be provided dynamically from the stream as well.
We can iterate further adding support to other controlnets, but this already adds the groundwork and
sets the patterns for how to do so.
```yaml
model_id: "KBlueLeaf/kohaku-v2.1"
t_index_list: [0, 16, 32]
width: 512
height: 512
device: "cuda"
dtype: "float16"
prompt: "an anime render of a girl with purple hair, masterpiece"
negative_prompt: "blurry, low quality, flat, 2d"
guidance_scale: 1.1
num_inference_steps: 50 …
```
=> streamdiffusion: Add controlnet support

runner/app/live/pipelines/streamdiffusion.py
We were only handling exceptions on initial pipeline load, on the process loop itself,
but on update it ended up without a pipeline object set up.
The annoying part is that we do have to freeze the inference anyway cause we dont have
VRAM to load 2 pipelines at once. So if you send invalid params it's gonna take a while.
=> streamdiffusion: Fallback to previous params on update failure

runner/app/live/pipelines/streamdiffusion.py, runner/app/tools/streamdiffusion/build_tensorrt_internal.sh, runner/dl_checkpoints.sh, runner/docker/Dockerfile.live-base-streamdiffusion
This upgrades the streamdiffusion lib to add support to the dynamic tensorrt engines.
This will allow us to switch resolution of the pipeline (i.e. between different streams) without
requiring a full reload, being much quicker.
=> streamdiffusion: Dynamic resolution TensorRT engines

runner/app/live/streamer/process_guardian.py
When changing resolution it can take more than 30s to reload the stream. Make sure we don't kill the process during that.
=> process_guardian: Increase params update timeout to 60s

runner/app/live/streamer/process_guardian.py
We want to be always quick in loading the default params for a new stream, so make sure we revert the stream back to the default when it is done.
=> process_guardian: Revert to default params after stream stops

runner/app/live/streamer/process_guardian.py
We made that general exception cause streamdiffusion was not being used and comfyui was supposed to get fixed. It never did and streamdiffusion is the priority now, so let's add a dirty check only for comfyui pipeline.
=> process: Only skip restart for comfyui

runner/app/live/streamer/process.py
At 24fps, each frame is ~41ms, so with just a couple in the queue plus the frames that are in-flight on either end of the pipeline, we're already looking at 100+ ms of latency.
Note that we would preferably have separate queues for audio and video but that's a larger change.
=> live: Minimize media queue sizes.

runner/dl_checkpoints.sh, runner/docker/Dockerfile.live-base-streamdiffusion
- Offline mode by default on the image
- On the dl_checkpoints script we disable it just in case any file is missing during compilation (most are downloaded by the script itself, but let's not be obnoxious)
=> streamdiffusion: Set HF to offline mode in runtime

runner/app/live/streamer/process_guardian.py
It might happen that we never get any input from the stream, we might be forever stuck in the
`DEGRADED_INPUT` state because of [this check](https://github.com/livepeer/ai-worker/blob/c3396d13f00d7d7bb4f831d3503ee0da44fb2005/runner/app/live/streamer/process_guardian.py#L199-L200) that comes before any timeout.
To fix it, I made sure we check for the input timeout before checking for the pipeline loading
conditions. The only side-effect I had to include was making the `time_since_last_input` start
as `0` when the pipeline starts, instead of "+INF" (`current_time`). I've corrected for this
on the only place that I think it'd matter, in the stream shutdown branch.
Implements ENG-3004
=> process: Ensure stream is stopped with no inputs

runner/app/live/pipelines/interface.py, runner/app/live/pipelines/streamdiffusion.py, runner/app/live/streamer/process.py
This makes sure we propagate internal errors when updating the parameters so that
feedback can be shown to the user. Made it through a special logging field to be added
when we want the error to go to the end user, like for the IPAdapter errors we are getting
in the library. This should not be abused as to become pure spam tho, only actionable/critical
or high-level errors should be reported to the user.
=> streamdiffusion: Report internal errors updating parameters

runner/app/live/pipelines/interface.py, runner/app/live/pipelines/streamdiffusion.py, runner/app/live/streamer/process.py, runner/app/live/streamer/process_guardian.py
This is to propagate the state of when the pipeline process is reloading the pipeline.
This is mainly useful for when the stream ends, where we reload the default params again.
In case these default params require a reload, this will now make sure that the Orchestrator
will not accept any streams while that reload is happening. 
This is the main PR for INF-297
=> live/pipeline: Propagate loading state upwards

runner/app/live/infer.py, runner/app/live/streamer/process.py, runner/app/live/streamer/process_guardian.py, runner/app/pipelines/live_video_to_video.py
This is to avoid having the pipeline process resist a restart when the parent process dies for any reason.
Fixed this in 2 ways:
- Ensure we gracefully stop the process guardian when we have an uncaught exception (cause of orphaned process recently)
- Make pipeline process kill itself when it notices the parent process is gone. This is implemented with a unix signal and a wathdog thread
Fixes INF-350
=> infer.py: Avoid leaving orphaned process behind
