livepeer/ai-runner

- .gitignore
- runner/.devcontainer/devcontainer.json
This pull request introduces a [dev container](https://code.visualstudio.com/docs/devcontainers/containers) configuration file, facilitating seamless development within the runner container. This enhancement simplifies the setup process and promotes a consistent development environment across the team.
> refactor: introduce dev container configuration

- .github/workflows/ai-runner-docker.yaml
This pull request prevents the docker container to be rebuild when we change the [Development Container
config](https://code.visualstudio.com/docs/devcontainers/containers).
> chore(devContainers): prevent Docker rebuild on changes

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/model_request.yml
- .github/ISSUE_TEMPLATE/pipeline_request.yml
This pull request introduces issue templates to streamline the submission process for bug reports and feature requests. With these templates in place, contributors will have clear guidance on how
> ci: implement issue templates for automated labeling

- runner/.devcontainer/devcontainer.json
- runner/dev/README.md
This pull request updates the development documentation to ensure that the right vscode config is used.
> docs: update development documentation

- runner/app/pipelines/image_to_video.py
- worker/container.go
- worker/docker.go
- worker/worker.go
This pull request enables users to pass optimization flags to the AI inference pipelines. Due to startup delays we currently only pass these flags to containers that are started warm.
> feat(worker): add optimization flags

- runner/gen_openapi.py
- runner/openapi.json
This pull request adds the servers field to the OpenAPI spec and makes the resulting JSON file human readable.
> feat(runner): add 'servers' to OpenAPI spec

- cmd/examples/image-to-image/main.go
- cmd/examples/image-to-video/main.go
- cmd/examples/text-to-image/main.go
These lines were generating errors in vscode. They appear related to #61 
They are just sample code and there might be a better way to fix than using stubs. Let me know what you think.
> Fix broken example code

- runner/app/pipelines/image_to_image.py
- runner/app/pipelines/text_to_image.py
- runner/dev/README.md
This pull request applies some small code and documentation formatting improvements.
> refactor: improve code formatting

- runner/dev/README.md
This pull request adds the prerequisites to the vscode dev container instructions.
> chore: update dev container instructions

- dev/README.md
- runner/dev/README.md
- runner/dev/patches/mock.patch
This pull request adds all the components needed to be able to mock the pipelines.
> chore: add pipeline mock development guide

- runner/dev/README.md
This pull request ensures that developers have all the steps needed to debug a ai-runner container when it is used in the go-livepeer library.
> docs: improve runner dev docs

- runner/app/dependencies.py
- runner/app/main.py
- runner/app/pipelines/image_to_image.py
- runner/app/pipelines/image_to_video.py
- runner/app/pipelines/optim/deepcache.py
- runner/app/pipelines/optim/sfast.py
- runner/app/pipelines/text_to_image.py
- runner/app/pipelines/upscale.py
- runner/app/pipelines/utils/utils.py
- runner/app/routes/image_to_image.py
- runner/app/routes/image_to_video.py
- runner/app/routes/text_to_image.py
- runner/app/routes/upscale.py
- runner/bench.py
- runner/modal_app.py
- runner/openapi.json
- worker/runner.gen.go
This pull request applies several code formatting improvements and replaces the hardcoded error codes by the error codes in the FastAPI status module.
> refactor: improve error codes and code formatting

- runner/app/pipelines/utils/utils.py
This pull request ensures that an empty dict is returned by the prompt splitter when no valid prompt was found.
> feat: improve prompt splitter

- runner/app/pipelines/image_to_image.py
- runner/app/pipelines/text_to_image.py
This pull request fixes some unet deprecation warnings by chaning the way the
stable diffusion base model is loaded.
> fix unet load deprecation warning

- runner/gateway.openapi.json
- runner/gen_openapi.py
- runner/openapi.gateway.json
This pull request improves the naming and generation for the OpenAPI spec so that they are easier to work with.
> feat: improve OpenAPI spec generation and naming

- runner/openapi.json
Reverts livepeer/ai-worker#156
> Revert "chore: remove redundant OpenAPI spec"

- .flake8
- runner/app/pipelines/optim/deepcache.py
- runner/app/pipelines/optim/sfast.py
- runner/app/pipelines/utils/__init__.py
- runner/app/pipelines/utils/audio.py
- runner/app/pipelines/utils/utils.py
- runner/app/routes/image_to_image.py
- runner/app/routes/image_to_video.py
- runner/app/routes/text_to_image.py
- runner/app/routes/upscale.py
- runner/bench.py
- runner/gateway.openapi.json
This pull request fixes flake8 errors that were introduced into the codebase in the last months.
> chore: fix flake8 errors

- runner/app/routes/audio_to_text.py
- runner/app/routes/image_to_image.py
- runner/app/routes/image_to_video.py
- runner/app/routes/text_to_image.py
- runner/app/routes/upscale.py
- runner/gateway.openapi.json
- runner/gateway.openapi.yaml
- runner/openapi.json
- runner/openapi.yaml
This pull request adds pipeline descriptions so that each pipeline is clearly explained on the docs.
> refactor: add pipeline descriptions

- runner/gen_openapi.py
This pull request replaces the default OpenAPI spec with yaml.
> refactor(openapi): replace json with yaml

- runner/app/routes/util.py
- runner/gateway.openapi.json
- runner/gateway.openapi.yaml
- runner/openapi.json
- runner/openapi.yaml
This pull request ensures that descriptions show up for the route response types in the docs.
> refactor: add response type descriptions

- worker/runner.gen.go
This pull request updates the go bindings to include the right docstrings.
> chore(worker): update go bindings

- runner/gen_openapi.py
This pull request ensures that the functions in the gen_openapi file are typed.
> refactor: type gen_openapi file

- runner/app/pipelines/audio_to_text.py
This pull request renames the self.ldm (Latent Diffusion Model) to self.tm (Transformer model) to make the distinction clearer.
> refactor: rename A2T pipeline attribute

- runner/gateway.openapi.yaml
- runner/gen_openapi.py
- runner/openapi.yaml
This pull request adds the studio Gateway to the list of servers.
> add studio api url

- .github/workflows/ai-runner-docker.yaml
This pull request ensures that developers can trigger docker image building.
> ci(docker): add workflow dispatch

- .github/workflows/ai-runner-docker.yaml
- .github/workflows/ai-runner-pipelines-docker.yaml
- runner/docker/Dockerfile.segment_anything_2
This pull requests add a new CI action to build the new pipeline specific docker containers.
> ci: add pipeline docker ci

- .github/workflows/ai-runner-pipelines-docker.yaml
This pull request ensures that the SAM2 docker has the right tags.
> ci(docker): add pipeline docker ci 2

- README.md
- runner/README.md
- runner/dl_checkpoints.sh
This pull request updates the code and documentation to signal we are entering the Beta phase of the AI network journey.
> chore: update alpha to beta phase

- README.md
@rickstaa just an FYI for you here. We'll be exploring realtime ai pipelines in this branch for now to get started.
> readme: update with note

- worker/worker.go
This pull request ensures that LoraLoadError is properly forwarded to the gateway, allowing better visibility of issues. A more comprehensive error handling mechanism can be implemented in a future pull request.
> refactor(ai): forward LoraLoadError to gateway

- runner/docker/Dockerfile.segment_anything_2
Pins the dependency on [facebook/sam2](https://github.com/facebookresearch/sam2) to unbreak our sam2 pipeline.
With our workflow pulling from upstream main, we encountered:
```
raise MissingConfigException(
hydra.errors.MissingConfigException: Cannot find primary config 'configs/sam2/sam2_hiera_l.yaml'. Check that it's in your config search path.
```
Others have reported this issue as well:
https://github.com/facebookresearch/sam2/issues/346
> Pin sam2 commit

- runner/app/main.py
- runner/app/pipelines/segment_anything_2.py
- runner/app/routes/utils.py
This pull request applies several code improvements to ensure the code is consistent between pipelines. It also ensures that the return type of the A2T pipeline is strictly typed.
> refactor(runner): apply small code improvements

- runner/gateway.openapi.yaml
- runner/openapi.yaml
- worker/runner.gen.go
This pull request updates the OpenAPI spec and golang client bindings so that they reflect the new changes introduced in https://github.com/livepeer/ai-worker/pull/246.
> chore: update OpenAPI spec and client bindings

- runner/docker/Dockerfile.segment_anything_2
This pull request mounts the app folder in the SAM2 pipeline container so that developers don't have to always rebuild the base container to get the latest changes.
> refactor(runner): improve SAM2 container dev experience

- runner/app/routes/live_video_to_video.py
- runner/app/routes/utils.py
- runner/gateway.openapi.yaml
- runner/openapi.yaml
- worker/runner.gen.go
This is needed for golang in https://github.com/livepeer/go-livepeer/pull/3211
> Add response params for live-video-to-video

- runner/app/live/streamer/streamer.py
Reload liveportrait more proactively, and also reload in background if input stopped but the model was stuck.
> live/infer: Improve process restart logic for stale pipeline

- runner/app/pipelines/image_to_image.py
- runner/app/pipelines/text_to_image.py
This pull request simplifies the ModelName class list method.
> refactor: simplify ModelName class

- runner/app/dependencies.py
- runner/app/main.py
- runner/app/pipelines/audio_to_text.py
- runner/app/pipelines/image_to_image.py
- runner/app/pipelines/image_to_text.py
- runner/app/pipelines/image_to_video.py
- runner/app/pipelines/segment_anything_2.py
- runner/app/pipelines/text_to_image.py
- runner/app/pipelines/text_to_speech.py
- runner/app/pipelines/upscale.py
- runner/app/pipelines/utils/__init__.py
- runner/app/routes/audio_to_text.py
- runner/app/routes/image_to_image.py
- runner/app/routes/image_to_text.py
- runner/app/routes/image_to_video.py
- runner/app/routes/segment_anything_2.py
- runner/app/routes/text_to_image.py
- runner/app/routes/text_to_speech.py
- runner/app/routes/upscale.py
- runner/bench.py
- runner/gen_openapi.py
- runner/modal_app.py
- runner/tests/routes/test_utils.py
This pull request applies black and isort formatting suggestions to the codebase.
> chore: apply formatter suggestions

- worker/docker.go
I'm 99% certain I've already done this, maybe got lost in some unmerged PR?
> worker: Add noop image to map

- runner/app/live/infer.py
This change fixes an issue that caused the control_url subscribe task to terminate early when starting inference
> Fix control_url task runner

- .github/workflows/ai-runner-test.yaml
This pull request adds a new GitHub action that runs the runner tests on main branch commits and pull requests.
> ci(runner): add runner test ci

- worker/docker.go
> worker: Fix typo breaking build

- .github/workflows/ai-runner-live-pipelines-docker.yaml
- runner/app/live/pipelines/comfyui.py
- runner/docker/Dockerfile.live-base-streamdiffusion
use prompt from params if present when the comfyui pipeline starts, add logging when prompt is set
> Init prompt from params

- .github/workflows/ai-runner-live-pipelines-docker.yaml
This pull request removes the cancel in context comment since it is the desired behavoir.
> ci(runner): remove cancel in context comment

- runner/dl_checkpoints.sh
- runner/docker/Dockerfile.live-base-comfyui
Add Florence 2 to comfyui container. 
Docker container builds locally and temporarily pushed to `adastravideo/ai-runner:live-app-comfyui` Tested locally through comfystream and runs only on first frame to select a point and when inputs change to the Florence2run node for task, text_input, annotation_color, and output_mask_select.
> feat: Add florence 2 to comfyui container

- .github/workflows/ai-runner-pipelines-fps-test.yaml
(other changes are from `prettierd` hook)
> workflow: Switch over to self-hosted gpu runner

- runner/docker/Dockerfile.live-base-comfyui
Includes PRs:
[fix: update point coords scaling for mask](https://github.com/pschroedl/ComfyUI-SAM2-Realtime/pull/4)
* [fix point coords scaling for mask](https://github.com/pschroedl/ComfyUI-SAM2-Realtime/pull/4/commits/0479c98a11395ce0154ddd96b79a188c76667d7f)[fix point coords scaling for mask](https://github.com/pschroedl/ComfyUI-SAM2-Realtime/pull/4/commits/0479c98a11395ce0154ddd96b79a188c76667d7f)
* [remove import not needed](https://github.com/pschroedl/ComfyUI-SAM2-Realtime/pull/4/commits/b29709c50d0362d8de7ee27fb3ddf64f0998b9ad)
and
[Unbreak old workflows and speedup](https://github.com/pschroedl/ComfyUI-SAM2-Realtime/pull/5)
* [make reset_tracking optional](https://github.com/pschroedl/ComfyUI-SAM2-Realtime/pull/5/commits/f4e56bd733d03d0b99702e18c829e6f0165ca72c) …
> Update Sam2 ComfyUI Node

- runner/docker/Dockerfile.live-base-comfyui
Add run mode input to Florence 2 node to select running on task change or every frame
> feat: update florence 2 to add run mode

- runner/dl_checkpoints.sh
Adjusting the script so it work also for AI Batch orchestrators
> dl_checkpoints.sh new --batch flag to install only sam2-hiera-large model

- runner/dl_checkpoints.sh
This will automatically pull the most recent runner images during the deployment.
> Pull runner images

- runner/dl_checkpoints.sh
@leszko this should fix the florence 2 models not found and the pipeline loads on the orchestrator i have ssh access to.
> update florence2 models download

- runner/dl_checkpoints.sh
We can't change user to `user` as it doesn't exist. So let's use root for generation, then change file ownership to the current user
> dl_checkpoints.sh run as root but chown to current user

- runner/dl_checkpoints.sh
- Add a `DEBUG` flag to script execution
- Pull the docker image needed for ComfyUI build process
- shellcheck/shellfmt auto-linting
> dl_checkpoints: QoL improvements

- runner/app/live/infer.py
- runner/app/live/log.py
- runner/app/live/streamer/process.py
- runner/app/live/streamer/protocol/trickle.py
- runner/app/live/trickle/decoder.py
- runner/app/live/trickle/encoder.py
- runner/app/live/trickle/frame.py
> latency logs

- runner/app/live/api/api.py
- runner/app/live/streamer/protocol/protocol.py
- runner/app/live/streamer/protocol/trickle.py
- runner/app/live/streamer/protocol/zeromq.py
- runner/app/live/streamer/streamer.py
- runner/app/live/trickle/media.py
- runner/docker/Dockerfile.live-app-noop
> feat: stream trace events

- runner/app/live/pipelines/comfyui.py
- runner/app/live/pipelines/interface.py
- runner/app/live/streamer/process.py
PR adds the functionality to stop comfyui when stopping the process
> feat: comfyui stop

- runner/app/live/pipelines/comfyui.py
- runner/app/live/pipelines/interface.py
- runner/app/live/streamer/process.py
Reverts livepeer/ai-runner#432
> Revert "feat: comfyui stop"

- runner/Dockerfile
- runner/app/runit/uvicorn/run
- runner/dev/Dockerfile.debug
- runner/docker/Dockerfile.audio_to_text
- runner/docker/Dockerfile.live-app-noop
- runner/docker/Dockerfile.live-app__PIPELINE__
- runner/docker/Dockerfile.llm
- runner/docker/Dockerfile.segment_anything_2
- runner/docker/Dockerfile.text_to_speech
- runner/requirements.live-ai.txt
We need IPv6 support on some of GPU clouds so enabling it by default in here.
> uvicorn to bind to all the interfaces; upgrade to 0.34.0

- runner/app/live/pipelines/comfyui.py
- runner/app/live/streamer/process.py
- runner/docker/Dockerfile.live-app__PIPELINE__
- runner/docker/Dockerfile.live-base-comfyui
Dockerfile.live-base-comfyui base image -> livepeer/comfyui-base:0.0.2-ai-runner
> Bump comfy base image version

- runner/dl_checkpoints.sh
Updates dl_checkpoints to include /workspace in the path to ComfyUI and comfystream per changes in the comfyUI base image reflected here https://github.com/livepeer/ai-runner/pull/430
> add /workspace to dl_checkpoints ComfyUI and comfystream paths

- runner/dl_checkpoints.sh
- runner/requirements.live-ai.txt
Following on from https://github.com/livepeer/ai-runner/pull/437, the script still wasn't working for me locally or in CI so these changes should fix it.
> Fix dl_checkpoints script

- runner/app/live/streamer/process_guardian.py
- runner/app/pipelines/live_video_to_video.py
This reverts commit c7520cb87f816446f087266e5c4b4c985a57aafc.
It didn't work so let's keep it off for now
> Revert "fix: process stderr (#450)"

- runner/app/live/trickle/media.py
Reverts livepeer/ai-runner#433
> Revert "Encode audio to Opus"

- runner/app/live/trickle/encoder.py
Using input sample rate caused problems when the input was in somethhing that Opus doesn't support like 44100hz
> Hard code sample rate to 48khz

- .github/workflows/ai-runner-docker.yaml
- .github/workflows/ai-runner-live-pipelines-docker.yaml
- .github/workflows/ai-runner-pipelines-docker.yaml
Reverts livepeer/ai-runner#457
> Revert "upgrade build-push-action to v6 to enable build summaries"

- .github/workflows/ai-runner-docker.yaml
- .github/workflows/ai-runner-live-pipelines-docker.yaml
- .github/workflows/ai-runner-pipelines-docker.yaml
Reverts livepeer/ai-runner#464
> Revert "Revert "upgrade build-push-action to v6 to enable build summaries""

- docs/live-ai-local-dev.md
- runner/app/live/Sam2Wrapper/__init__.py
- runner/app/live/Sam2Wrapper/wrapper.py
- runner/app/live/StreamDiffusionWrapper/__init__.py
- runner/app/live/StreamDiffusionWrapper/build_tensorrt.py
- runner/app/live/StreamDiffusionWrapper/wrapper.py
- runner/app/live/infer.py
- runner/app/live/pipelines/loader.py
- runner/app/live/pipelines/segment_anything_2.py
- runner/app/live/pipelines/streamdiffusion.py
- runner/dl_checkpoints.sh
- runner/docker/Dockerfile.live-app__PIPELINE__
- runner/docker/Dockerfile.live-base-segment_anything_2
- runner/docker/Dockerfile.live-base-streamdiffusion
- runner/run-lv2v.sh
Reverts livepeer/ai-runner#461
> Revert "deprecate: old pipelines"

- runner/app/live/infer.py
- runner/app/live/log.py
- runner/app/live/streamer/process.py
adds a check to remove an extra try for loading the pipeline if the params update doesn't have prompt
> fix: remove extra try

- runner/app/live/streamer/process.py
fixes the following error, pipeline loading is skipped if the update_params is to update request_id and stream_id
```
26/03/2025, 10:55:44
Error processing frame: 'NoneType' object has no attribute 'process_frame'
26/03/2025, 10:55:54
Error processing frame: 'NoneType' object has no attribute 'process_frame'
26/03/2025, 10:56:04
Error processing frame: 'NoneType' object has no attribute 'process_frame'
26/03/2025, 10:56:14
Error processing frame: 'NoneType' object has no attribute 'process_frame'
```
> fix: pipeline loading

- runner/app/live/pipelines/comfyui.py
The existing one was failing to load on my dev environment. I'm not sure where is the
source of truth for the default pipeline on Daydream app, so I just picked one that I saw
from the production logs which I think is probably the default. That fixed my local env.
Would be good for someone with access to the source of truth to double check this.
> live/comfyui: Fix default prompt

- runner/app/live/trickle/media.py
Until we figure out what is making the process stop
> Disable encoder retries for now

- runner/app/live/streamer/process_guardian.py
**Context** ([Discord](https://discord.com/channels/423160867534929930/1353942041960251445/1354984208006643732))
After #483, on the startup of the runner, it is going to return `ONLINE` ("busy") for 90s, as if there was something flowing even though it obviously starts idle. This doesn't cause huge issues since the worker will not move an idle runner to "borrowed" because of the healthcheck, only the other way around (here's the [state machine](https://github.com/livepeer/go-livepeer/blob/master/doc/worker.md#ai-worker)). It can be misleading anyway so I was looking for a fix.
It was going to get fixed by #485, but we don't go through with that, so I'm submitting this separate fix.
**Changes**
- Changed the initial `self.status` to have a `start_time=0` so that we fallback to the old …
> live/proc_guard: Make sure healthcheck starts as OFFLINE

- .github/workflows/ai-runner-live-pipelines-docker.yaml
Same as #494 but missed some references.
> .github: Fix other tj-actions/changed-files references

- .github/workflows/ai-runner-docker.yaml
- .github/workflows/ai-runner-live-pipelines-docker.yaml
- .github/workflows/ai-runner-pipelines-docker.yaml
> ai-runner-*pipelines-docker github workflows - update github runner ubuntu

- runner/Dockerfile
- runner/docker/Dockerfile.audio_to_text
- runner/docker/Dockerfile.live-app__PIPELINE__
- runner/docker/Dockerfile.live-base
- runner/docker/Dockerfile.live-base-comfyui
- runner/docker/Dockerfile.llm
- runner/docker/Dockerfile.text_to_speech
I believe that not all of these Dockerfiles/images are being used but let's introduce unified optimisations everywhere.
Proper optimisations would include separating heavy builds requiring additional system packages into separate Docker stages. But that's more complex task
> Docker image optimisation

- runner/app/live/streamer/process.py
- runner/app/live/streamer/process_guardian.py
- runner/app/live/streamer/streamer.py
Don't always wait 60s+30s for the runner teardown.
> Improve the teardown time

- runner/Dockerfile
- runner/docker/Dockerfile.audio_to_text
- runner/docker/Dockerfile.live-app__PIPELINE__
- runner/docker/Dockerfile.live-base
- runner/docker/Dockerfile.live-base-comfyui
- runner/docker/Dockerfile.llm
- runner/docker/Dockerfile.text_to_speech
Reverts livepeer/ai-runner#498
> Revert "Docker image optimisation"

- .dockerignore
- .github/workflows/ai-runner-models.yaml
- runner/docker/Dockerfile.models
In here we just build a docker image with huggingface models:
* batch - we just pull the models and save in the image
* live - we pull the models and run tensorrt for a given GPU
In this PR I don't bake it into ai-runner:live... image yet. I've started to combine these two on a separate [PR](https://github.com/livepeer/ai-runner/pull/502/files)
> Tensorrt RTX 4090 models in docker

- runner/dl_checkpoints.sh
- runner/docker/Dockerfile.live-base-comfyui
updates dl_checkpoints with a build of a dynamic version of the dreamshaper tensorrt engine supporting vertical/horizontal resolutions of 704x448
> add build of dynamic trt dreamshaper engine

- runner/dl_checkpoints.sh
This change builds an additional depth-anything engine using the new model `depth_anything_v2_vitl.onnx` added in https://github.com/livepeer/comfystream/pull/79
> add depth-anything-2-large compilation to dl_checkpoints

- .github/workflows/ai-runner-noop-docker.yaml
- .github/workflows/comfyui-docker.yaml
- runner/app/live/infer.py
Since we skip the base image build when unchanged, we can't always set the docker digest on the base image. So only specify if it is present.
> .github: Fix docker image build on PRs

- runner/app/live/trickle/decoder.py
- runner/app/live/trickle/frame.py
Upon implementing #564 and trying to understand the code involved, I fixed a few typing
issues I was getting on my IDE. This might help maintenance of these files (I still want to 
add some mypy/linter at some point).
> live/trickle: Typing improvements

- .github/workflows/comfyui-docker.yaml
https://discord.com/channels/423160867534929930/1371641872149250138/1371641876477906964
> Fix typo where duplicate docker image tag was being pushed

- .github/workflows/ai-runner-models.yaml
- runner/dl_checkpoints.sh
- runner/docker/Dockerfile.live-base-comfyui
This change bumps livepeer/comfyui-base to match the comfystream feature branch https://github.com/livepeer/comfystream/pull/142 which adds new models and custom node for live portrait workflows
dl_checkpoints.sh is also updated to compile tensorrt engines
> add FasterLivePortrait TRT build to dl_checkpoints

- runner/dl_checkpoints.sh
- runner/docker/Dockerfile.live-base-comfyui
Reverts livepeer/ai-runner#557
Reverting because it broke the staging
> Revert "add FasterLivePortrait TRT build to dl_checkpoints"

- runner/app/live/api/api.py
- runner/app/live/infer.py
- runner/app/live/streamer/process.py
- runner/app/live/streamer/process_guardian.py
- runner/app/live/streamer/protocol/protocol.py
- runner/app/live/streamer/status.py
- runner/app/live/streamer/streamer.py
- runner/app/pipelines/base.py
- runner/app/pipelines/live_video_to_video.py
- runner/openapi.yaml
There is something wrong with the following PRs, so reverting them. @victorges could you please take a look, test and re-apply them again?
- https://github.com/livepeer/ai-runner/pull/568
- https://github.com/livepeer/ai-runner/pull/580
- https://github.com/livepeer/ai-runner/pull/583
> Revert a few PRs to fix our staging

- runner/docker/Dockerfile.live-base-comfyui
Bump comfyui-base to resolve issue with handling invalid prompts. Includes https://github.com/livepeer/comfystream/pull/245
> update comfyui-base to cancel running prompts

- runner/gateway.openapi.yaml
- runner/openapi.yaml
Update openapi spec auto gen files for version bump
cc @leszko
> update openapi spec for new version

- runner/dl_checkpoints.sh
Fix after https://github.com/livepeer/ai-runner/pull/649
> dl_checkpoints: Separate comfyui tensorrt build

- runner/app/live/pipelines/streamdiffusion.py
Simple integration with feature already on streamdiffusion lib
> streamddifusion: Support prompt and seed blending

- runner/app/live/pipelines/streamdiffusion.py
These are handled separately from the other stream params so let's implement it too
> streamdiffusion: Update controlnets scale dynammically

- runner/dl_checkpoints.sh
adduser: Please enter a username matching the regular expression configured via the NAME_REGEX[_SYSTEM] configuration variable.  Use the `--force-badname' option to relax this check or reconfigure NAME_REGEX. failed ComfyUI setup_models.py
> dl_checkpoints: Bring back -n on adduser/chown

- runner/dl_checkpoints.sh
Reverts livepeer/ai-runner#686
> Revert "dl_checkpoints: Bring back -n on adduser/chown"

- runner/requirements.llm.in
> bump vllm version for llm pipeline

- runner/app/live/pipelines/streamdiffusion.py
- runner/requirements.live-ai.txt
We were getting some cryptic behavior without this. Just like this description.
Fixes INF-275
> streamdiffusion: Add some explicit validation for t_index_list

- runner/app/live/pipelines/streamdiffusion_params.py
- runner/dl_checkpoints.sh
- runner/docker/Dockerfile.live-base-streamdiffusion
https://github.com/livepeer/StreamDiffusion/pull/122
> streamdiffusion: Update to Freepik nsfw detector

- .github/workflows/streamdiffusion-docker.yaml
- runner/app/live/pipelines/streamdiffusion_sdxl_default_params.json
- runner/app/live/pipelines/streamdiffusion_sdxl_faceid_default_params.json
- One pre-loaded with `regular` IP-Adapter (`streamdiffusion-sdxl`), and 
- The other pre-loaded with the `faceid` IP-Adapter (`streamdiffusion-sdxl-faceid`)
> streamdiffusion: Create separate SDXL images

- runner/app/live/trickle/encoder.py
This usually causes the muxer to blow up and throw an exception.
Prevent this blow up by dropping the frame instead.
Mostly seems to occur with poorly prepared audio inputs, but it could happen to video as well.
> live: Drop out-of-order frames before muxing.
